### ISSUE TITLE
how to support it in ARM

### ISSUE THREAD

**Issue by thunderZH963** [tcp-acceleration-service/FlexTOE#2]
I want to run this project on the arm V8. But SSE)https://github.com/DLTcollab/sse2neon/ can be used to solve)/"cpuid.h not found"/ asm and other problems are emerging one after another. 
Is there any version supported by ARM, or any suggestions for modification?
Thank you and look forward to your reply.

**Comment by rajathshashidhara** [comment]
I presume that the host platform is ARM in your case. Here are some tips for porting:
1. [RTE](https://github.com/tcp-acceleration-service/FlexTOE/tree/main/include/rte) is borrowed from DPDK. There should be equivalent ARM versions of the files in DPDK. For example: https://github.com/DPDK/dpdk/tree/main/lib/eal/arm
2. Commits on this branch might help with CRC/RDTSC/Prefetch instructions: https://github.com/rajathshashidhara/tas/commits/bluefield-aarch64-pipeline
